version: 2.1

executors:
  default:
    working_directory: ~/app
    docker:
      - image: circleci/ruby:2.5-node-browsers
        environment:
          RAILS_ENV: test
          REVIEWDOG_VERSION: 0.9.11

commands:
  bundle_install:
    steps:
      # Restore bundle cache
      - restore_cache:
          key: bundle-cache-{{ checksum "Gemfile.lock" }}
      # Bundle install dependencies
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      # Store bundle cache
      - save_cache:
          key: bundle-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

jobs:
  setup:
    executor:
      name: default
    steps:
      - checkout
      - bundle_install
  rspec:
    executor:
      name: default
    steps:
      - checkout
      - bundle_install

      # Database setup
      - run: bundle exec rails db:create db:schema:load
      # RSpec
      - run: bundle exec rspec

      - store_artifacts:
          path: coverage
      - store_artifacts:
          path: tmp/capybara
  rubocop:
    executor:
      name: default
    steps:
      - checkout
      - bundle_install
      - run:
          name: Install reviewdog
          command: |
            curl -fSL https://github.com/haya14busa/reviewdog/releases/download/$REVIEWDOG_VERSION/reviewdog_linux_amd64 -o reviewdog && chmod +x ./reviewdog

      # RuboCop
      - run: bundle exec rubocop
      - run: bundle exec rubocop | ./reviewdog -f=rubocop -reporter=github-pr-review

workflows:
  test:
    jobs:
      - setup
      - rspec:
          requires:
            - setup
      - rubocop:
          requires:
            - setup
